name: CI/CD Pipeline for MongoDB

on:
  push:
    branches:
      - main
      - add-tests
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        volumes:
          - ./src/__tests__/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21

      - name: Install dependencies
        run: npm install

      - name: Run Server and Wait for it to start and start testing
        run: |
          npm run dev &
          sleep 15
          npm run test
        env:
          MONGO_URI: mongodb://root:example@localhost:27017/
          CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          BASE_URL: http://localhost:5005
